# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cdjm2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jiemian(object):
    def setupUi(self, jiemian):
        jiemian.setObjectName("jiemian")
        jiemian.resize(1099, 616)
        jiemian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout_8 = QtWidgets.QGridLayout(jiemian)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_24 = QtWidgets.QLabel(jiemian)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.label = QtWidgets.QLabel(jiemian)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("image: url(E:/张博睿-冲动攻击识别/packagetry/jmtb/北理工.jpeg);")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(jiemian)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout.setStretch(3, 2)
        self.gridLayout_8.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 15, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(jiemian)
        self.label_14.setStyleSheet("image: url(package/情绪.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(jiemian)
        self.label_15.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.emo = QtWidgets.QLabel(jiemian)
        self.emo.setText("")
        self.emo.setObjectName("emo")
        self.horizontalLayout_6.addWidget(self.emo)
        self.label_19 = QtWidgets.QLabel(jiemian)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(jiemian)
        self.label_5.setStyleSheet("image: url(package/心率.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(jiemian)
        self.label_8.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.bpm = QtWidgets.QLabel(jiemian)
        self.bpm.setText("")
        self.bpm.setObjectName("bpm")
        self.horizontalLayout_8.addWidget(self.bpm)
        self.label_7 = QtWidgets.QLabel(jiemian)
        self.label_7.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(jiemian)
        self.label_17.setStyleSheet("image: url(package/waveform_path_ecg.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(jiemian)
        self.label_18.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_5.addWidget(self.label_18)
        self.score = QtWidgets.QLabel(jiemian)
        self.score.setText("")
        self.score.setObjectName("score")
        self.horizontalLayout_5.addWidget(self.score)
        self.label_20 = QtWidgets.QLabel(jiemian)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(jiemian)
        self.label_10.setStyleSheet("image: url(package/S_健康呼吸首页.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(jiemian)
        self.label_12.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.br = QtWidgets.QLabel(jiemian)
        self.br.setText("")
        self.br.setObjectName("br")
        self.horizontalLayout_7.addWidget(self.br)
        self.label_9 = QtWidgets.QLabel(jiemian)
        self.label_9.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(jiemian)
        self.label_2.setStyleSheet("image: url(package/血氧.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(jiemian)
        self.label_6.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.SpO2 = QtWidgets.QLabel(jiemian)
        self.SpO2.setText("")
        self.SpO2.setObjectName("SpO2")
        self.horizontalLayout_9.addWidget(self.SpO2)
        self.label_16 = QtWidgets.QLabel(jiemian)
        self.label_16.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QLabel(jiemian)
        self.frame.setStyleSheet("")
        self.frame.setText("")
        self.frame.setAlignment(QtCore.Qt.AlignCenter)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.xianshi = QtWidgets.QLabel(jiemian)
        self.xianshi.setStyleSheet("QLabel#label_2{\n"
"    font-family:\"楷体\";\n"
"    font-size:20px\n"
"}")
        self.xianshi.setText("")
        self.xianshi.setAlignment(QtCore.Qt.AlignCenter)
        self.xianshi.setObjectName("xianshi")
        self.verticalLayout.addWidget(self.xianshi)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(100, -1, 70, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.progressBar = QtWidgets.QProgressBar(jiemian)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_12.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout_8.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.detect_Name = QtWidgets.QLabel(jiemian)
        self.detect_Name.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:24px;\n"
"    color:white;\n"
"}")
        self.detect_Name.setText("")
        self.detect_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.detect_Name.setObjectName("detect_Name")
        self.horizontalLayout_2.addWidget(self.detect_Name)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(30, 20, -1, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.kaishi = QtWidgets.QPushButton(jiemian)
        self.kaishi.setStyleSheet("QPushButton#kaishi{\n"
"    font-size:20px;\n"
"    font-family:\"楷体\";\n"
"}")
        self.kaishi.setObjectName("kaishi")
        self.horizontalLayout_10.addWidget(self.kaishi)
        self.jieshu = QtWidgets.QPushButton(jiemian)
        self.jieshu.setStyleSheet("QPushButton#jieshu{\n"
"    font-size:20px;\n"
"    font-family:\"楷体\"\n"
"}")
        self.jieshu.setObjectName("jieshu")
        self.horizontalLayout_10.addWidget(self.jieshu)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.history = QtWidgets.QPushButton(jiemian)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(-1)
        self.history.setFont(font)
        self.history.setStyleSheet("QPushButton{\n"
"    font-size:24px;\n"
"    font-family:\"楷体\";\n"
"}")
        self.history.setObjectName("history")
        self.horizontalLayout_4.addWidget(self.history)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(jiemian)
        self.label_4.setStyleSheet("QLabel{\n"
"    font-family:\"楷体\";\n"
"    font-size:15px\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 5)
        self.verticalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout_8.setColumnStretch(1, 1)
        self.gridLayout_8.setRowStretch(0, 100)
        self.gridLayout_8.setRowStretch(1, 360)
        self.gridLayout_8.setRowStretch(2, 150)

        self.retranslateUi(jiemian)
        QtCore.QMetaObject.connectSlotsByName(jiemian)

    def retranslateUi(self, jiemian):
        _translate = QtCore.QCoreApplication.translate
        jiemian.setWindowTitle(_translate("jiemian", "Form"))
        self.label_3.setText(_translate("jiemian", "智能巡情系统"))
        self.label_15.setText(_translate("jiemian", "emotion"))
        self.label_8.setText(_translate("jiemian", "bpm"))
        self.label_18.setText(_translate("jiemian", "hrv"))
        self.label_12.setText(_translate("jiemian", "br"))
        self.label_6.setText(_translate("jiemian", "SpO2"))
        self.kaishi.setText(_translate("jiemian", "开始"))
        self.jieshu.setText(_translate("jiemian", "结束"))
        self.history.setText(_translate("jiemian", "更多历史数据"))
        self.label_4.setText(_translate("jiemian", "BIT"))
import jiemiantubiao_rc
