# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ceshi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jiemian(object):
    def setupUi(self, jiemian):
        jiemian.setObjectName("jiemian")
        jiemian.resize(1138, 642)
        self.centralWidget = QtWidgets.QWidget(jiemian)
        self.centralWidget.setObjectName("centralWidget")
        self.background = QtWidgets.QFrame(self.centralWidget)
        self.background.setGeometry(QtCore.QRect(60, 40, 1011, 571))
        self.background.setStyleSheet("QFrame#background{\n"
"    background-color:qlineargradient(x0:0, y0:1,x1:1, y1:1,stop:0.4 rgb(107,128,210),stop:1 rgb(180,140,255));\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.frame_2 = QtWidgets.QFrame(self.background)
        self.frame_2.setGeometry(QtCore.QRect(240, 0, 771, 571))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color:rgba(245,249,254);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.kaishi = QtWidgets.QPushButton(self.frame_2)
        self.kaishi.setGeometry(QtCore.QRect(100, 50, 110, 40))
        self.kaishi.setStyleSheet("QPushButton#kaishi{\n"
"    font-size:20px;\n"
"    font-family:\"楷体\"\n"
"}")
        self.kaishi.setObjectName("kaishi")
        self.jieshu = QtWidgets.QPushButton(self.frame_2)
        self.jieshu.setGeometry(QtCore.QRect(250, 50, 110, 40))
        self.jieshu.setStyleSheet("QPushButton#jieshu{\n"
"    font-size:20px;\n"
"    font-family:\"楷体\"\n"
"}")
        self.jieshu.setObjectName("jieshu")
        self.tishi = QtWidgets.QLabel(self.frame_2)
        self.tishi.setGeometry(QtCore.QRect(100, 110, 281, 61))
        self.tishi.setStyleSheet("QLabel#tishi{\n"
"    \n"
"}")
        self.tishi.setText("")
        self.tishi.setObjectName("tishi")
        self.xianshi = QtWidgets.QLabel(self.frame_2)
        self.xianshi.setGeometry(QtCore.QRect(440, 460, 261, 61))
        self.xianshi.setText("")
        self.xianshi.setObjectName("xianshi")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(430, 210, 291, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setStyleSheet("QLabel#label_7{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.bpm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bpm.setText("")
        self.bpm.setObjectName("bpm")
        self.gridLayout.addWidget(self.bpm, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("QLabel#label_3{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("QLabel#label_2{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("QLabel#label_5{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.score = QtWidgets.QLabel(self.gridLayoutWidget)
        self.score.setText("")
        self.score.setObjectName("score")
        self.gridLayout.addWidget(self.score, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setStyleSheet("QLabel#label_4{\n"
"    font-family:\"楷体\";\n"
"    font-size:30px\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.emo = QtWidgets.QLabel(self.gridLayoutWidget)
        self.emo.setText("")
        self.emo.setObjectName("emo")
        self.gridLayout.addWidget(self.emo, 1, 1, 1, 2)
        self.frame = QtWidgets.QLabel(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(30, 200, 370, 280))
        self.frame.setStyleSheet("QLabel#frame{\n"
"    alignment：Aligncenter;\n"
"    background-color:rgb(170, 255, 255)\n"
"}")
        self.frame.setText("")
        self.frame.setAlignment(QtCore.Qt.AlignCenter)
        self.frame.setObjectName("frame")
        self.Quit = QtWidgets.QPushButton(self.frame_2)
        self.Quit.setGeometry(QtCore.QRect(580, 50, 110, 40))
        self.Quit.setStyleSheet("QPushButton#Quit{\n"
"    font-size:20px;\n"
"    font-family:\"楷体\"\n"
"}")
        self.Quit.setObjectName("Quit")
        self.peopleImgFrame = QtWidgets.QFrame(self.background)
        self.peopleImgFrame.setGeometry(QtCore.QRect(60, 30, 120, 120))
        self.peopleImgFrame.setStyleSheet("QFrame#peopleImgFrame{\n"
"    padding:5px;\n"
"    background-color:rgb(255,255,255);\n"
"    border-radius:30px\n"
"}")
        self.peopleImgFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.peopleImgFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.peopleImgFrame.setObjectName("peopleImgFrame")
        self.peopleImg = QtWidgets.QLabel(self.peopleImgFrame)
        self.peopleImg.setGeometry(QtCore.QRect(0, 0, 120, 120))
        self.peopleImg.setStyleSheet("QLabel#peopleImg{\n"
"    padding:5px;\n"
"    background-color:rgb(255,255,255);\n"
"    border-radius:30px\n"
"}")
        self.peopleImg.setText("")
        self.peopleImg.setObjectName("peopleImg")
        self.detect_Name = QtWidgets.QLabel(self.background)
        self.detect_Name.setGeometry(QtCore.QRect(40, 180, 171, 61))
        self.detect_Name.setStyleSheet("QLabel#label{\n"
"    padding-left:40px;\n"
"    background-color:rgb(255,255,255);\n"
"    border-radius:30px\n"
"}")
        self.detect_Name.setObjectName("detect_Name")
        jiemian.setCentralWidget(self.centralWidget)

        self.retranslateUi(jiemian)
        self.Quit.clicked.connect(jiemian.close)
        QtCore.QMetaObject.connectSlotsByName(jiemian)

    def retranslateUi(self, jiemian):
        _translate = QtCore.QCoreApplication.translate
        jiemian.setWindowTitle(_translate("jiemian", "MainWindow"))
        self.kaishi.setText(_translate("jiemian", "开始"))
        self.jieshu.setText(_translate("jiemian", "结束"))
        self.label_7.setText(_translate("jiemian", "分"))
        self.label_3.setText(_translate("jiemian", "表情"))
        self.label_2.setText(_translate("jiemian", "心率"))
        self.label_5.setText(_translate("jiemian", "次/分"))
        self.label_4.setText(_translate("jiemian", "得分"))
        self.Quit.setText(_translate("jiemian", "退出"))
        self.detect_Name.setText(_translate("jiemian", "检测中"))
