# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_History(object):
    def setupUi(self, History):
        History.setObjectName("History")
        History.resize(973, 508)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(History.sizePolicy().hasHeightForWidth())
        History.setSizePolicy(sizePolicy)
        self.tableWidget = QtWidgets.QTableWidget(History)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 971, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(31)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(History)
        QtCore.QMetaObject.connectSlotsByName(History)

    def retranslateUi(self, History):
        _translate = QtCore.QCoreApplication.translate
        History.setWindowTitle(_translate("History", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("History", "时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("History", "心率"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("History", "呼吸率"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("History", "血氧"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("History", "情绪"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("History", "心率变异性"))
